/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsVehicleTrackingRouteImport } from './routes/products.vehicle-tracking'
import { Route as ProductsPersonalTrackingRouteImport } from './routes/products.personal-tracking'
import { Route as ProductsEmployeeTrackingRouteImport } from './routes/products.employee-tracking'
import { Route as ProductsDispatchRouteImport } from './routes/products.dispatch'
import { Route as ProductsDashCamRouteImport } from './routes/products.dash-cam'
import { Route as ProductsAssetTrackingRouteImport } from './routes/products.asset-tracking'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsVehicleTrackingRoute = ProductsVehicleTrackingRouteImport.update({
  id: '/products/vehicle-tracking',
  path: '/products/vehicle-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPersonalTrackingRoute =
  ProductsPersonalTrackingRouteImport.update({
    id: '/products/personal-tracking',
    path: '/products/personal-tracking',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsEmployeeTrackingRoute =
  ProductsEmployeeTrackingRouteImport.update({
    id: '/products/employee-tracking',
    path: '/products/employee-tracking',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsDispatchRoute = ProductsDispatchRouteImport.update({
  id: '/products/dispatch',
  path: '/products/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDashCamRoute = ProductsDashCamRouteImport.update({
  id: '/products/dash-cam',
  path: '/products/dash-cam',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAssetTrackingRoute = ProductsAssetTrackingRouteImport.update({
  id: '/products/asset-tracking',
  path: '/products/asset-tracking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/products/asset-tracking': typeof ProductsAssetTrackingRoute
  '/products/dash-cam': typeof ProductsDashCamRoute
  '/products/dispatch': typeof ProductsDispatchRoute
  '/products/employee-tracking': typeof ProductsEmployeeTrackingRoute
  '/products/personal-tracking': typeof ProductsPersonalTrackingRoute
  '/products/vehicle-tracking': typeof ProductsVehicleTrackingRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/products/asset-tracking': typeof ProductsAssetTrackingRoute
  '/products/dash-cam': typeof ProductsDashCamRoute
  '/products/dispatch': typeof ProductsDispatchRoute
  '/products/employee-tracking': typeof ProductsEmployeeTrackingRoute
  '/products/personal-tracking': typeof ProductsPersonalTrackingRoute
  '/products/vehicle-tracking': typeof ProductsVehicleTrackingRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/products/asset-tracking': typeof ProductsAssetTrackingRoute
  '/products/dash-cam': typeof ProductsDashCamRoute
  '/products/dispatch': typeof ProductsDispatchRoute
  '/products/employee-tracking': typeof ProductsEmployeeTrackingRoute
  '/products/personal-tracking': typeof ProductsPersonalTrackingRoute
  '/products/vehicle-tracking': typeof ProductsVehicleTrackingRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/company'
    | '/contact'
    | '/industries'
    | '/login'
    | '/shop'
    | '/products/asset-tracking'
    | '/products/dash-cam'
    | '/products/dispatch'
    | '/products/employee-tracking'
    | '/products/personal-tracking'
    | '/products/vehicle-tracking'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/company'
    | '/contact'
    | '/industries'
    | '/login'
    | '/shop'
    | '/products/asset-tracking'
    | '/products/dash-cam'
    | '/products/dispatch'
    | '/products/employee-tracking'
    | '/products/personal-tracking'
    | '/products/vehicle-tracking'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/company'
    | '/contact'
    | '/industries'
    | '/login'
    | '/shop'
    | '/products/asset-tracking'
    | '/products/dash-cam'
    | '/products/dispatch'
    | '/products/employee-tracking'
    | '/products/personal-tracking'
    | '/products/vehicle-tracking'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  ProductsAssetTrackingRoute: typeof ProductsAssetTrackingRoute
  ProductsDashCamRoute: typeof ProductsDashCamRoute
  ProductsDispatchRoute: typeof ProductsDispatchRoute
  ProductsEmployeeTrackingRoute: typeof ProductsEmployeeTrackingRoute
  ProductsPersonalTrackingRoute: typeof ProductsPersonalTrackingRoute
  ProductsVehicleTrackingRoute: typeof ProductsVehicleTrackingRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/vehicle-tracking': {
      id: '/products/vehicle-tracking'
      path: '/products/vehicle-tracking'
      fullPath: '/products/vehicle-tracking'
      preLoaderRoute: typeof ProductsVehicleTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/personal-tracking': {
      id: '/products/personal-tracking'
      path: '/products/personal-tracking'
      fullPath: '/products/personal-tracking'
      preLoaderRoute: typeof ProductsPersonalTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/employee-tracking': {
      id: '/products/employee-tracking'
      path: '/products/employee-tracking'
      fullPath: '/products/employee-tracking'
      preLoaderRoute: typeof ProductsEmployeeTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/dispatch': {
      id: '/products/dispatch'
      path: '/products/dispatch'
      fullPath: '/products/dispatch'
      preLoaderRoute: typeof ProductsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/dash-cam': {
      id: '/products/dash-cam'
      path: '/products/dash-cam'
      fullPath: '/products/dash-cam'
      preLoaderRoute: typeof ProductsDashCamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/asset-tracking': {
      id: '/products/asset-tracking'
      path: '/products/asset-tracking'
      fullPath: '/products/asset-tracking'
      preLoaderRoute: typeof ProductsAssetTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  ProductsAssetTrackingRoute: ProductsAssetTrackingRoute,
  ProductsDashCamRoute: ProductsDashCamRoute,
  ProductsDispatchRoute: ProductsDispatchRoute,
  ProductsEmployeeTrackingRoute: ProductsEmployeeTrackingRoute,
  ProductsPersonalTrackingRoute: ProductsPersonalTrackingRoute,
  ProductsVehicleTrackingRoute: ProductsVehicleTrackingRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
